image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

- name: Grant execute permission for gradlew
        run: chmod +x gradlew

install:

  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации
