image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки
install:

<<<<<<< HEAD
  - test --info  # запускаем тест, флаг --info позволяет выводить больше информации
=======



  -  test --info  # запускаем тест, флаг --info позволяет выводить больше информации
>>>>>>> dc3406863229cd5ccbf66c0993363a872778fb1b
